<?php

use Illuminate\Database\Seeder;

class PropertySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = $this->getData();

        foreach ($data as $datum) {
            $property = new \App\Models\Property([
                'id' => $datum[0],
                'suburb' => $datum[1],
                'state' => $datum[2],
                'country' => $datum[3],
                'guid' => \Illuminate\Support\Str::uuid()
            ]);

            $property->save();
        }
    }

    /**
     * Parsed data from xlsx file via 3ty service
     *
     * @return array
     */
    private function getData() {
        return array(
                array(
                    '1',
                    'Parramatta',
                    'NSW',
                    'Australia'
                ),
                array(
                    '2',
                    'Parramatta',
                    'NSW',
                    'Australia'
                ),
                array(
                    '3',
                    'Parramatta',
                    'NSW',
                    'Australia'
                ),
                array(
                    '4',
                    'Parramatta',
                    'NSW',
                    'Australia'
                ),
                array(
                    '5',
                    'Parramatta',
                    'NSW',
                    'Australia'
                ),
                array(
                    '6',
                    'Parramatta',
                    'NSW',
                    'Australia'
                ),
                array(
                    '7',
                    'Parramatta',
                    'NSW',
                    'Australia'
                ),
                array(
                    '8',
                    'Parramatta',
                    'NSW',
                    'Australia'
                ),
                array(
                    '9',
                    'Parramatta',
                    'NSW',
                    'Australia'
                ),
                array(
                    '10',
                    'Parramatta',
                    'NSW',
                    'Australia'
                ),
                array(
                    '11',
                    'Parramatta',
                    'NSW',
                    'Australia'
                ),
                array(
                    '12',
                    'Parramatta',
                    'NSW',
                    'Australia'
                ),
                array(
                    '13',
                    'Parramatta',
                    'NSW',
                    'Australia'
                ),
                array(
                    '14',
                    'Parramatta',
                    'NSW',
                    'Australia'
                ),
                array(
                    '15',
                    'Ryde',
                    'NSW',
                    'Australia'
                ),
                array(
                    '16',
                    'Ryde',
                    'NSW',
                    'Australia'
                ),
                array(
                    '17',
                    'Ryde',
                    'NSW',
                    'Australia'
                ),
                array(
                    '18',
                    'Ryde',
                    'NSW',
                    'Australia'
                ),
                array(
                    '19',
                    'Ryde',
                    'NSW',
                    'Australia'
                ),
                array(
                    '20',
                    'Castle Hill',
                    'NSW',
                    'Australia'
                ),
                array(
                    '21',
                    'Richmond',
                    'NSW',
                    'Australia'
                ),
                array(
                    '22',
                    'Richmond',
                    'NSW',
                    'Australia'
                ),
                array(
                    '23',
                    'Richmond',
                    'NSW',
                    'Australia'
                ),
                array(
                    '24',
                    'Richmond',
                    'NSW',
                    'Australia'
                ),
                array(
                    '25',
                    'Richmond',
                    'NSW',
                    'Australia'
                ),
                array(
                    '26',
                    'Richmond',
                    'NSW',
                    'Australia'
                ),
                array(
                    '27',
                    'Richmond',
                    'NSW',
                    'Australia'
                ),
                array(
                    '28',
                    'Richmond',
                    'NSW',
                    'Australia'
                ),
                array(
                    '29',
                    'Richmond',
                    'NSW',
                    'Australia'
                ),
                array(
                    '30',
                    'Richmond',
                    'NSW',
                    'Australia'
                ),
                array(
                    '31',
                    'Richmond',
                    'NSW',
                    'Australia'
                ),
                array(
                    '32',
                    'Richmond',
                    'NSW',
                    'Australia'
                ),
                array(
                    '33',
                    'Richmond',
                    'NSW',
                    'Australia'
                ),
                array(
                    '34',
                    'Richmond',
                    'NSW',
                    'Australia'
                ),
                array(
                    '35',
                    'Richmond',
                    'NSW',
                    'Australia'
                ),
                array(
                    '36',
                    'Richmond',
                    'NSW',
                    'Australia'
                ),
                array(
                    '37',
                    'Southbank',
                    'Qld',
                    'Australia'
                ),
                array(
                    '38',
                    'Southbank',
                    'Qld',
                    'Australia'
                ),
                array(
                    '39',
                    'Southbank',
                    'Qld',
                    'Australia'
                ),
                array(
                    '40',
                    'Southbank',
                    'Qld',
                    'Australia'
                ),
                array(
                    '41',
                    'Southbank',
                    'Qld',
                    'Australia'
                ),
                array(
                    '42',
                    'Southbank',
                    'Qld',
                    'Australia'
                ),
                array(
                    '43',
                    'Southbank',
                    'Qld',
                    'Australia'
                ),
                array(
                    '44',
                    'Southbank',
                    'Qld',
                    'Australia'
                ),
                array(
                    '45',
                    'Southbank',
                    'Qld',
                    'Australia'
                ),
                array(
                    '46',
                    'Southbank',
                    'Qld',
                    'Australia'
                ),
                array(
                    '47',
                    'Southbank',
                    'Qld',
                    'Australia'
                ),
                array(
                    '48',
                    'Southbank',
                    'Qld',
                    'Australia'
                ),
                array(
                    '49',
                    'O\'Sullivan Beach',
                    'Qld',
                    'Australia'
                ),
                array(
                    '50',
                    'O\'Sullivan Beach',
                    'Qld',
                    'Australia'
                ),
                array(
                    '51',
                    'O\'Sullivan Beach',
                    'Qld',
                    'Australia'
                ),
                array(
                    '52',
                    'O\'Sullivan Beach',
                    'Qld',
                    'Australia'
                ),
                array(
                    '53',
                    'O\'Sullivan Beach',
                    'Qld',
                    'Australia'
                ),
                array(
                    '54',
                    'O\'Sullivan Beach',
                    'Qld',
                    'Australia'
                ),
                array(
                    '55',
                    'O\'Sullivan Beach',
                    'Qld',
                    'Australia'
                ),
                array(
                    '56',
                    'O\'Sullivan Beach',
                    'Qld',
                    'Australia'
                ),
                array(
                    '57',
                    'Geelong',
                    'Vic',
                    'Australia'
                ),
                array(
                    '58',
                    'Geelong',
                    'Vic',
                    'Australia'
                ),
                array(
                    '59',
                    'Geelong',
                    'Vic',
                    'Australia'
                ),
                array(
                    '60',
                    'Geelong',
                    'Vic',
                    'Australia'
                ),
                array(
                    '61',
                    'Geelong',
                    'Vic',
                    'Australia'
                ),
                array(
                    '62',
                    'Geelong',
                    'Vic',
                    'Australia'
                ),
                array(
                    '63',
                    'Geelong',
                    'Vic',
                    'Australia'
                ),
                array(
                    '64',
                    'Geelong',
                    'Vic',
                    'Australia'
                ),
                array(
                    '65',
                    'Geelong',
                    'Vic',
                    'Australia'
                ),
                array(
                    '66',
                    'Geelong',
                    'Vic',
                    'Australia'
                ),
                array(
                    '67',
                    'Geelong',
                    'Vic',
                    'Australia'
                ),
                array(
                    '68',
                    'Geelong',
                    'Vic',
                    'Australia'
                ),
                array(
                    '69',
                    'Geelong',
                    'Vic',
                    'Australia'
                ),
                array(
                    '70',
                    'Geelong',
                    'Vic',
                    'Australia'
                ),
                array(
                    '71',
                    'Geelong',
                    'Vic',
                    'Australia'
                ),
                array(
                    '72',
                    'Geelong',
                    'Vic',
                    'Australia'
                ),
                array(
                    '73',
                    'Fitzroy',
                    'Vic',
                    'Australia'
                ),
                array(
                    '74',
                    'Richmond',
                    'Vic',
                    'Australia'
                ),
                array(
                    '75',
                    'Richmond',
                    'Vic',
                    'Australia'
                ),
                array(
                    '76',
                    'Richmond',
                    'Vic',
                    'Australia'
                ),
                array(
                    '77',
                    'Richmond',
                    'Vic',
                    'Australia'
                ),
                array(
                    '78',
                    'Richmond',
                    'Vic',
                    'Australia'
                ),
                array(
                    '79',
                    'Richmond',
                    'Vic',
                    'Australia'
                ),
                array(
                    '80',
                    'Richmond',
                    'Vic',
                    'Australia'
                ),
                array(
                    '81',
                    'Richmond',
                    'Vic',
                    'Australia'
                ),
                array(
                    '82',
                    'Richmond',
                    'Vic',
                    'Australia'
                ),
                array(
                    '83',
                    'Richmond',
                    'Vic',
                    'Australia'
                ),
                array(
                    '84',
                    'Richmond',
                    'Vic',
                    'Australia'
                ),
                array(
                    '85',
                    'Richmond',
                    'Vic',
                    'Australia'
                ),
                array(
                    '86',
                    'Richmond',
                    'Vic',
                    'Australia'
                ),
                array(
                    '87',
                    'Richmond',
                    'Vic',
                    'Australia'
                ),
                array(
                    '88',
                    'Richmond',
                    'Vic',
                    'Australia'
                ),
                array(
                    '89',
                    'Richmond',
                    'Vic',
                    'Australia'
                ),
                array(
                    '90',
                    'Richmond',
                    'Vic',
                    'Australia'
                ),
                array(
                    '91',
                    'Richmond',
                    'Vic',
                    'Australia'
                ),
                array(
                    '92',
                    'Richmond',
                    'Vic',
                    'Australia'
                ),
                array(
                    '93',
                    'Subiaco',
                    'WA',
                    'Australia'
                ),
                array(
                    '94',
                    'Subiaco',
                    'WA',
                    'Australia'
                ),
                array(
                    '95',
                    'Subiaco',
                    'WA',
                    'Australia'
                ),
                array(
                    '96',
                    'Subiaco',
                    'WA',
                    'Australia'
                ),
                array(
                    '97',
                    'Subiaco',
                    'WA',
                    'Australia'
                ),
                array(
                    '98',
                    'Subiaco',
                    'WA',
                    'Australia'
                ),
                array(
                    '99',
                    'Subiaco',
                    'WA',
                    'Australia'
                ),
                array(
                    '100',
                    'Subiaco',
                    'WA',
                    'Australia'
                )
            );
    }
}
